name: Release Process

on:
  workflow_dispatch:
    inputs:
      auto_merge:
        description: 'Automatically merge the release PR if checks pass'
        required: false
        default: false
        type: boolean
      manual_release:
        description: 'Manually release an already-finalized version (skips prepare, goes straight to publish)'
        required: false
        default: false
        type: boolean
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    uses: SOFware/reissue/.github/workflows/shared-ruby-gem-release.yml@main
    with:
      gem_name: pundit-plus
      version_file_path: lib/pundit/plus/version.rb
      ruby_version: ruby
      git_user_email: gems@sofwarellc.com
      git_user_name: SOFware
      auto_merge: ${{ inputs.auto_merge || false }}
      manual_release: ${{ inputs.manual_release || false }}
      use_trusted_publishing: false